### PR TITLE
Add new options

### PR DESCRIPTION
**Pull request by iddanh**
- new option to set rel attribute on links
- new option to allow non hex values on color attributes
- add css classes to background attribute

### CODE REVIEW

**Comment by nozer** [comment]
Hi Iddan,

First, thank you for the contribution!
Here are some improvements that is needed to merge this request. 
1 - Ensure valid color names: all alpha and no more than 50 characters 
2 - Remove `allowNonHex: this.options.allowNonHex`. This is unnecessary if we are checking against valid color values (i.e. name or hex)
3 - Ensure valid rel attribute: either u can check against valid rel attr values from a hard coded list or ensure it is alpha only and less than 30 chars.
4 - Making css classes from background attribute doesn't seem like a good idea. Imagine someone passed {background: "#f1f1f1", ...} and this would result in a class name like "{prefix}-background-#f1f1f1" which is not right. If you really need this ability, I would suggest that you add a new flag to converter like `allowBackgroundClasses` and then make background classes only when that flag is true. This way only those who know what they are doing would enable it. You can even improve it further and make it like `allowBackgroundClasses=['p','span']` etc so you can allow it only for the selected tags.

**Comment by iddanh** [comment]
Hi Nozer,
Thanks for the quick reply.
I implemented your improvement suggestions, but for point number 4 I didn't implement your suggestion because at that stage of the code we still don't know what html tag it is going to be.
What I did instead was to filter out the non color literal values for the background property, that way we won't get class names like `{prefix}-background-#f1f1f1`. I think this is a good solution, tell me what you think.

Unfortunately I couldn't get the tests to run locally on my machine, I get the following error:
```
$ npm test

> quill-delta-to-html@0.5.0 test C:\dev\quill-delta-to-html
> ./node_modules/nyc/bin/nyc.js ./node_modules/mocha/bin/mocha --compilers ts:ts-node/register -b "./test/**/*.ts"

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```
Thanks

**Comment by nozer** [comment]
Everyone may not want their background property values to be converted to class. Even quill is not doing it as far as I have seen. This is something that is specific to your case. So, we cannot assume everyone will want their literal background values to be classes. So, at the least, you should add a flag like `allowBackgroundClasses` and only when it is set to true, you should add the class. And when you do that, you should not add it as style property as well. It should be mutually exclusive not to pollute the generated html with meaningless style values for background if they are being used as classes.

Also a few minor improvement suggestions:
`return !!colorStr.match(/^[a-zA-Z]{1,50}$/i);` if you are using `/i` flag, which stands for ignore case, you don't need to add `A-Z` as `/i` will take care of it. 

`return !!relStr.match(/^[a-zA-Z\-]{1,30}$/i);` `rel` attribute values are just alpha and they are listed [here](https://www.w3.org/TR/html5/links.html#linkTypes) and it can contain multiple values separated by spaces; so you can remove the dash from regex and put space there. Same comment goes for `/i` and `A-Z` as above. 

I do not know why it gives that error for you. Did you do `npm install` and then also can you install browerify globally? Then try again? :) Thanks

**Comment by iddanh** [comment]
I implemented your suggestions, and finally got tests working!

BTW it is possible in quill to use background properties as class instead of inline, as specified [here](http://quilljs.com/guides/how-to-customize-quill/#class-vs-inline), but you are right that it should be opt-in.

Also I allowed `\-` in the regex because followed the values that were listed [here](https://www.w3schools.com/Tags/att_link_rel.asp), but you are right so I removed it.

Thanks

**Comment by nozer** [comment]
Looks good and thanks!

**Comment by iddanh** [comment]
Can you release the changes on npm?
Thanks

**Comment by nozer** [comment]
Oh I forgot. Will do

Nihat

**Comment by nozer** [comment]
I have just published on npm. I have been sick since Sunday and forgot all about this. Terribly sorry for the delay.

**Comment by iddanh** [comment]
Thanks!

**Pull request merged**
