### PR TITLE
Custom block, tag, css, attrs and styles

### PR DESCRIPTION
**Pull request by volser**

### CODE REVIEW

**Comment by volser** [comment]
@nozer I have added new cool features, can you check please

**Comment by volser** [comment]
should resolve this one
https://github.com/nozer/quill-delta-to-html/issues/68

**Comment by volser** [comment]
one thing, need to fix docs

**Comment by nozer** [comment]
Sorry for being late. Don't you have the right to merge? If now, how can I give you full rights to merge as you wish? I already like the way you work and I really don't have time for this repo.

**Comment by volser** [comment]
@nozer hey, I have rights for repo, but I don't have access to npm to publish new versions

**Comment by nozer** [comment]
I added you (@volser) as owner to the npm package. Tag / publish as you wish. I don't have time for this. It is practically on your hands now.

**Comment by bulby97** [comment]
@volser do you plan to release this PR soon ?

**Comment by volser** [comment]
@bulby97 need to fix README for new methods, are you able to help with it?

were added

```
customTag?: (format: string, op: DeltaInsertOp) => string | void;
  customTagAttributes?: (
    op: DeltaInsertOp
  ) => {
    [key: string]: string;
  } | void;
  customCssClasses?: (op: DeltaInsertOp) => string | string[] | void;
  customCssStyles?: (op: DeltaInsertOp) => string | string[] | void;
```

**Comment by volser** [comment]
pushed new version

**Comment by julianlam** [comment]
@volser `customCssClasses` doesn't seem to be called for `inline-group` group types, only for `list` (and probably the other ones, haven't checked)... is this by design?

**Comment by volser** [comment]
@julianlam  Are you able to write tests to reproduce it?

**Pull request merged**
