### PR TITLE
Add "justify" align type.

### PR DESCRIPTION
**Pull request by joaomarcoslopes**

### CODE REVIEW

**Comment by rienswagerman** [comment]
+1

**Comment by joaomarcoslopes** [comment]
@nozer Can you check it, please? I've a production issue to solve with this PR. Thanks!

**Comment by nozer** [comment]
Done, terribly sorry for the delay!

**Comment by joaoaraujo-hotmart** [comment]
@nozer What is the next step to a build and get updated dist files?

**Pull request merged**
