### PR TITLE
Expose op to html converter

### PR DESCRIPTION
**Pull request by kfirzuberi**

### CODE REVIEW

**Comment by kfirzuberi** [comment]
@nozer LMK what you think

**Comment by nozer** [comment]
Exposing it means I would have to be careful about changing its methods / properties in the future. I don't want to put myself under that burden . Why do you need it?

**Comment by kfirzuberi** [comment]
I need to use the function `OpToHtmlConverter.getTagAttributes` outside in the `renderCustomWith` for example (instead of calculating the style);

```
        converter.renderCustomWith(handleCustomTypes);

	function handleCustomTypes(customOp, contextOp) {
		var otc = new OpToHtmlConverter(customOp, config);
		var style = otc.getTagAttributes().....
		switch (customOp.insert.type) {
			case 'mention':
				var val = customOp.insert.value;
				return '<span id="' + val.id + '">' + val.value + '</span>';
			case 'action':
				return '<a nohref onClick="alert(123)">' + customOp.insert.value.type + '</a>';
			default:
				return '';
		}
	}
```

**Comment by nozer** [comment]
Ok. I see. I will expose a few methods including the one you use from that class. I will push the modifications later.

**Pull request merged**
